/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_blerf_ftl_parser_random_NativeRandomJNI */

#ifndef _Included_net_blerf_ftl_parser_random_NativeRandomJNI
#define _Included_net_blerf_ftl_parser_random_NativeRandomJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_blerf_ftl_parser_random_NativeRandomJNI
 * Method:    native_rand
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_blerf_ftl_parser_random_NativeRandomJNI_native_1rand
  (JNIEnv *, jobject);

/*
 * Class:     net_blerf_ftl_parser_random_NativeRandomJNI
 * Method:    native_srand
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_blerf_ftl_parser_random_NativeRandomJNI_native_1srand
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
